### ISSUE TITLE
Please release this package

### ISSUE THREAD

**Issue by rgov** [adafruit/Adafruit_CircuitPython_PIO_UART#1]
It looks like it's almost ready to go, and it would be a great addition to CircuitPython to be able to easily take advantage of the RP2040's PIO capabilities for extra UARTs.

**Comment by FoamyGuy** [comment]
initial release exists now.

**Comment by DarylWM** [comment]
Thank you for this package. I'm not able to install it on my Pico though. Using `circup install adafruit_pio_uart` yields the error `adafruit_pio_uart is not a known CircuitPython library`. I'm using CircuitPython 9.1.3, circup 2.0.4.

**Comment by tannewt** [comment]
`circup` will pick it up in the next 24 hours. It was added to the bundle here: https://github.com/adafruit/Adafruit_CircuitPython_Bundle/pull/475
